
-- Table: CITY
CREATE TABLE CITY (
    CNAME VARCHAR2(15) NOT NULL PRIMARY KEY,
    STATE VARCHAR2(15),
    COUNTRY VARCHAR2(30)
);

-- Table: AIRPORT
CREATE TABLE AIRPORT (
    AP_NAME VARCHAR2(100) NOT NULL PRIMARY KEY,
    STATE VARCHAR2(15),
    COUNTRY VARCHAR2(30),
    CNAME VARCHAR2(15),
    FOREIGN KEY (CNAME) REFERENCES CITY(CNAME) ON DELETE CASCADE
);

-- Table: AIRLINE
CREATE TABLE AIRLINE (
    AIRLINEID VARCHAR(3) NOT NULL PRIMARY KEY,
    AL_NAME VARCHAR2(50),
    THREE_DIGIT_CODE VARCHAR(3)
);

-- Table: FLIGHT
CREATE TABLE FLIGHT (
    FLIGHT_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    SOURCE VARCHAR(3),
    DESTINATION VARCHAR(3),
    ARRIVAL VARCHAR2(10),
    DEPARTURE VARCHAR2(10),
    STATUS VARCHAR(10),
    DURATION VARCHAR2(30),
    FLIGHTTYPE VARCHAR(10),
    LAYOVER_TIME VARCHAR2(30),
    NO_OF_STOPS INT,
    AIRLINEID VARCHAR(3),
    FOREIGN KEY (AIRLINEID) REFERENCES AIRLINE(AIRLINEID) ON DELETE CASCADE
);

-- Table: PASSENGER1 (PID, PASSPORT)
CREATE TABLE PASSENGER1 (
    PID INT NOT NULL,
    PASSPORTNO VARCHAR(10) NOT NULL,
    PRIMARY KEY (PID, PASSPORTNO)
);

-- Table: PASSENGER2 (Detailed Info)
CREATE TABLE PASSENGER2 (
    PASSPORTNO VARCHAR(10) NOT NULL PRIMARY KEY,
    FNAME VARCHAR2(20),
    M VARCHAR(1),
    LNAME VARCHAR2(20),
    ADDRESS VARCHAR2(100),
    PHONE INT,
    AGE INT,
    SEX VARCHAR(1)
);

-- Table: TICKET2
CREATE TABLE TICKET2 (
    DATE_OF_BOOKING DATE NOT NULL,
    SOURCE VARCHAR(3) NOT NULL,
    DESTINATION VARCHAR(3) NOT NULL,
    CLASS VARCHAR2(15) NOT NULL,
    PRICE INT,
    PRIMARY KEY (DATE_OF_BOOKING, SOURCE, DESTINATION, CLASS)
);
