
-- Procedure 1: DFW Economy Passengers
CREATE OR REPLACE PROCEDURE DFWECONOMYPASSENGERS AS
  CURSOR ECOPASSDETAILS IS
    SELECT al.AL_NAME, fl.FLIGHT_CODE, p2.FNAME, p2.LNAME, p2.PASSPORTNO,
           t.CLASS, t.DATE_OF_TRAVEL, t.DESTINATION, t.SOURCE, t.SEATNO, t.TICKET_NUMBER
    FROM Airline al, Flight fl, PASSENGER1 p1, PASSENGER2 p2, PASSENGER3 p3, TICKET1 t
    WHERE al.AIRLINEID = fl.AIRLINEID
      AND p1.PID = p3.PID
      AND p1.PASSPORTNO = p2.PASSPORTNO
      AND fl.FLIGHT_CODE = p3.FLIGHT_CODE
      AND t.PASSPORTNO = p2.PASSPORTNO
      AND t.CLASS = 'ECONOMY'
      AND t.DESTINATION = 'DFW';
  PASSDETAILS ECOPASSDETAILS%ROWTYPE;
BEGIN
  OPEN ECOPASSDETAILS;
  LOOP
    FETCH ECOPASSDETAILS INTO PASSDETAILS;
    EXIT WHEN ECOPASSDETAILS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(PASSDETAILS.AL_NAME || ' ' || PASSDETAILS.FLIGHT_CODE || ' ' ||
                         PASSDETAILS.FNAME || ' ' || PASSDETAILS.LNAME || ' ' || PASSDETAILS.PASSPORTNO);
  END LOOP;
  CLOSE ECOPASSDETAILS;
END;

-- Procedure 2: Flights By Status
CREATE OR REPLACE PROCEDURE FLIGHTSBYSTATUS(IN_STATUS IN VARCHAR2) AS
  CURSOR fSTATUS IS
    SELECT DISTINCT F.FLIGHT_CODE, AL.AL_NAME, F.ARRIVAL, F.DEPARTURE,
           F.SOURCE, F.DESTINATION, F.STATUS, F.FLIGHTTYPE
    FROM AIRLINE AL, FLIGHT F
    WHERE AL.AIRLINEID = F.AIRLINEID AND F.STATUS = IN_STATUS;
  FlightStatus fSTATUS%ROWTYPE;
BEGIN
  OPEN fSTATUS;
  LOOP
    FETCH fSTATUS INTO FlightStatus;
    EXIT WHEN fSTATUS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(FlightStatus.FLIGHT_CODE || ' ' || FlightStatus.AL_NAME || ' ' ||
                         FlightStatus.ARRIVAL || ' ' || FlightStatus.DEPARTURE || ' ' ||
                         FlightStatus.SOURCE || ' ' || FlightStatus.DESTINATION || ' ' ||
                         FlightStatus.STATUS || ' ' || FlightStatus.FLIGHTTYPE);
  END LOOP;
  CLOSE fSTATUS;
END;
